### ISSUE TITLE
Oki Responses

### ISSUE THREAD

**Issue by nickoki** [ga-wdi-exercises/shaping-up-with-angular#10]
- A **Module** is the home for our Angular program. It contains the pieces of application including dependencies on other modules.
- A **Controller** is where we define our application's behavior (functions and values). It helps us move data onto the user-facing page.
- Angular **Data Binding** is the connection between HTML elements and JavaScript code that allows data to be updated without a traditional page reload.
- A **Directive** is an Angular HTML tag that references a specified controller. It allows specific JavaScript functions to be run.
- An **Angular Expression** (i.e., {{ }}) is Angular's syntax for embedding data passed from the controllers.
- A **View Model** assists our application's data binding by providing scope to controller(s).

**Comment by nolds9** [comment]
👍
