### ISSUE TITLE
BK shaping_up_with_angular

### ISSUE THREAD

**Issue by bkeating55** [ga-wdi-exercises/shaping-up-with-angular#11]
Module - This is where we hold the all the pieces to our app

Controller - defines the application controller and holds the data for the application

Data Binding - synchronization between the model and the view

Directive - a function that executes when found in the DOM

Angular Expression (i.e., {{ }}) - Javascript like snippets that are used for interpolation

View Model - the scope in Angular. More specifically the relationship between the view and the model

**Comment by nolds9** [comment]
👍
