### ISSUE TITLE
Alex Manno - Intro to Angular

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/shaping-up-with-angular#15]
Module - A module is the container in which all the angular code for a page is written.  It creates the connection between the javascript logic and the html on the page.

Container - A container defines the behavior between the javascript elements of the page and the html.

Data Binding - The connection between javascript and HTML in the controller which allows the HTML elements to be manipulated.

Directive - A marker on a tag of html that corresponds to a logical javascript function. (Kind of thought about this as proteins and enzymes.)

Angular Expression -  Just the Syntax involved in calling an Angular function.  Contains data or strings.

View Model - A model that defines a specific controller to manipulate.  It provides scope to data binding.

**Comment by nolds9** [comment]
👍
