### ISSUE TITLE
Shaping up with Angular, Khoi

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/shaping-up-with-angular#17]
**Module:** Where we write pieces of our Angular application. 
    -How we keep our code encapsulated. It makes it more maintainable and where we define dependencies.

**Controller:** Help us get data onto page. Where we define our apps behavior by defining functions and values.

**Angular Expression (i.e., {{ }})** : allows us to insert dynamic values into your HTML. 
   ex. <p> {{"Hello " + "Angular!"}} </p>

**Data-Binding:** Allows HTML  elements to be changed based on the AngularJS logic in the related controller.

**Directive:** A marker on a HTML tag that tells angular to run or reference some JS code. It "Data-binds" the HTML and the controller. Its how we "bind the behavior."

**View Model:** the html dom element that the angular controller outputs to or affects.

**Comment by nolds9** [comment]
👍
