### ISSUE TITLE
Kevin Mahoney HW: October 21

### ISSUE THREAD

**Issue by kjmahoney** [ga-wdi-exercises/shaping-up-with-angular#18]
A directive is a marker on a HTML tag that tells Angular to run or reference some JavaScript code. It is what binds the behavior between our html and our javascript functions.

Modules are where we write pieces of our Angular application with the goal of encapsulating it. 

Expressions allow you to insert dynamic values into your HTML. They are denoted with {{ }} They are like the <%%> tags in ruby? 

Controllers are where we define our apps behavior by defining functions and values. They help us get data on our page  

Data-binding allows for expressions to be reevaluated when a property changes.

A view model creates a placeholder where a corresponding view can be placed based on the configuration,

**Comment by nolds9** [comment]
👍
