### ISSUE TITLE
Bedig Galladian

### ISSUE THREAD

**Issue by bgalladian** [ga-wdi-exercises/shaping-up-with-angular#24]
Module
-Where we write pieces of our Angular Application
-Makes code more readable and maintainable
-Where we define dependencies

Controller
-Help us get data onto the page
-Where we define applications behavior
-We add application behavior

Data Binding
-2 way data binding means expressions are re-evaluated when a property changes

Directive
-A marker on a HTML tag that tells Angular to run or reference some JS code. 
-Multiple directives for multiple actions
-HTML annotations that trigger JS behaviors 

Angular Expression (i.e., {{ }})
-Allow you to insert dynamic values into your HTML
-How values get displayed within the page

View Model
-The HTML dom element that the angular controller outputs to/manipulates.

**Comment by AndyWhitley** [comment]
👍
