### ISSUE TITLE
Nyketha's Angular HW

### ISSUE THREAD

**Issue by Nykke** [ga-wdi-exercises/shaping-up-with-angular#25]
- Angular helps build responsive websites that are dynamic and fast. 
- A client side JS framework for adding html.
- Uses bootstrap

Definitions to Know: 

* Module: Where we write pieces of Angular application, it is how we keep code encapsulated. It makes our code more paintable, testable, and readable. It’s also where we define dependencies for our applications.
		— var app = angular.module(‘store’, [ ]); 

* Controller: Where we define out apps behavior by defining functions and values. It’s stored within the module. It also called the gems.
		— app.controller(‘StoreController’, function(){
	this.product = gem; 
});                                         ^^^^ is always capital case. 
		— the scoop of the controller is always inside the div it’s stored in, if an expression is placed outside of it, the expression will not be called.
		— holds directive and expressions

* Data Binding: in Angular, expressions define a 2-Way Data Binding meaning the expressions are re-evaluated when a property changes.
		— ng-init allows us to evaluate an expression in the current scope

* Directive: a marker on an HTML tag that tells Angular to run or reference some JS code
		— ng-controller=“StoreController as store” 
		— this also holds our expressions
		— directives holds if/else statements(falsey and true)
		— can iterate through arrays 
		— can run filter functions through directives 

* Angular Expression (i.e., {{ }}): Allow you to insert dynamic values int  your HTML 
		— <p>
				I am {{ 4 + 6 }}
			</p> 
		— <p> 
				{{“hello” + “ you”}}
			</p> 

		— define a 2-Way Data Binding… expressions are re-evaluated when a property changes. 

* View Model: The HTML dom element that the angular controller manipulates

* Panel controller: holds all of our directive code just so it’s not so messy (if you placed it into the actual controller itself)

**Comment by superbuggy** [comment]
View Model: I would say it's a messenger between the model and the views. These answers are fantastic though! 👌 💅 nail'd it
