### ISSUE TITLE
Angular (Mike)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/shaping-up-with-angular#26]
Module: it is where we write pieces of our application. It makes our code more readable, maintainable, and testable. It’s also where we define the dependencies for the application.

Controller: are where we define our apps behavior by defining functions and values.

Data Binding: it is the automatic synchronization of data between the model and view components. 

Directive: it is a marker on an HTML tag that tells Angular to run on reference some JS code.

Angular Expression: allows you to insert dynamic values into your html

View Model: it is the scope object which you can access from either the controller or the view

**Comment by nayana487** [comment]
👍
