### ISSUE TITLE
shaping-up-with-angular application / spaces / isaac duarte

### ISSUE THREAD

**Issue by Philocoder93** [ga-wdi-exercises/shaping-up-with-angular#27]
Comfort 5/5 (big picture wise) 

Completeness 2/5 (my motivation is totally gone)

Modules: Where we write the 'meat' of our code, makes code more maintainable, testable etc. (can establish dependancies, modules inherit from other modules).
Directives: How we add behavior to our apps in angular.
Expressions: Expressions are how we add dynamically generated behavior to our angular apps.
Controllers: Controllers are what we write in order to get data onto the page.

**Comment by nayana487** [comment]
👍
