### ISSUE TITLE
Wes Coffay Deliverable

### ISSUE THREAD

**Issue by justwes2** [ga-wdi-exercises/shaping-up-with-angular#28]
Module- where pieces of angular app are written. Makes code easily testable
Controller- define application behavior by defining functions and values. 
Data Binding- expressions are reevaluated when a property changes
Directive- maker in html that references js code
Angular Expression (i.e., {{ }})- insert dynamic expressions into HTML
View Model- the staging area between the view (angularJS and HTML) and the angularJS models that control the logic.

**Comment by amaseda** [comment]
:+1:
