### ISSUE TITLE
Adam Whitehurst Homework

### ISSUE THREAD

**Issue by nairul** [ga-wdi-exercises/shaping-up-with-angular#29]
Directive = A marker on an HTML tag that tells Angular to run or reference some Javascript code.
Module = Where we write pieces of our Angular application. Makes our code more maintainable, testable, readable. Where we define dependencies for our app.
Expression = Allow you to insert dynamic values into our HTML
Controller = Where we define our applications behavior by defining functions and values
Data Binding = Connects the model and the view?
View Model = I don't really understand!

**Comment by nayana487** [comment]
👍
