### ISSUE TITLE
Laura G- Shaping Up with Angular

### ISSUE THREAD

**Issue by laurkgol** [ga-wdi-exercises/shaping-up-with-angular#32]
•	Module- where you write pieces of the Angular application including dependencies of app
•	Controller- where you define the app's behavior by defining functions and values
•	Data Binding- adding data to html 
•	Directive- how behavior is binded to page
•	Angular Expression (i.e., {{ }})- allows to you insert dynamic values into HTML
•	View Model- binds the form element value to the property

**Comment by AndyWhitley** [comment]
👍
