### ISSUE TITLE
Lisa Burr

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-exercises/shaping-up-with-angular#35]
**Module:** Encapsulated pieces of code that makes the overall code more maintainable, testable and readable.  Dependencies of the app are defined in modules as well.

**Controller:** Define the app’s behavior by defining functions and values.  The scope of the controller is only within the DOM element it is identified with.

**Data Binding:** Expressions are reevaluated when a property changes

**Directive:** A directive is a marker on an HTML tag that tells Angular to run or reference some JavaScript code.  Directives are how the behavior between HTML and JS is bound together.

**Angular Expression (i.e., {{ }}):** Expressions are used to insert dynamic values such as numerical operations and string operations into HTML.  

**View Model:** Model View Whatever −  AngularJS does not implement MVC in the traditional sense, but rather something closer to MVVM (Model-View-ViewModel). The Angular JS team refers it humorously as Model View Whatever.

**Comment by superbuggy** [comment]
Essentially the ViewModel is a messenger between the View and the Model, and is what implements 2-way data binding.

NICE work! 👍
