### ISSUE TITLE
Taylor Scott - Angular Intro HW

### ISSUE THREAD

**Issue by taylorscott91** [ga-wdi-exercises/shaping-up-with-angular#36]
Module: pieces of Angular application to make code more readable and testable. Also where we develop dependencies for pieces of code.

Controller: defines app's behavior by defining functions and values.

Data Binding: synchronization between the model and the view.

Directive: an attribute for HTML elements that creates data binding between it and the controller.

Angular Expression (i.e., {{ }}): contains the data passed in from the controller to the displayed HTML.

View Model: data that is shown to the user and which they interact with on the web page.

**Comment by AndyWhitley** [comment]
👍
