### ISSUE TITLE
Will Hawkins

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/shaping-up-with-angular#37]
Module: Where we write pieces of our Angular app. Makes code maintainable, testable, and readable. Where we define dependencies for our app.

Controller: Where we define our app's behavior by defining functions and values

Data Binding: This means expressions are reevaluated when a property changes

Directive: a marker on an HTML tag that tells Angular to run or reference some JavaScript code

Angular Expression: Allows you to insert dynamic values into your HTML

View Model:  I got kind of tired and decided to be unconscious after 2.7, but I never saw this anywhere

I'm finding that I need a serious JavaScript refresher! I'm SO excited for this though! THE MOST EXCITED!

**Comment by nayana487** [comment]
👍
