### ISSUE TITLE
Shaping Up With Angular HW - Vince Campanale 

### ISSUE THREAD

**Issue by vincecampanale** [ga-wdi-exercises/shaping-up-with-angular#38]
Module: 3 primary roles of Modules --
  1) "Where we write pieces of our Angular application"
  2) "Makes our code more maintainable, testable, and readable"
  3) "Where we define dependencies for our app"

Controller: "Help us get data onto the page" - "Where we define our application's behavior by defining functions and values"

Data Binding: Expressions are re-evaluated when properties change. 

Directive: "A marker on an HTML tag that tells Angular to run or reference some Javascript code." In other words, it's an indicator to Angular, embedded in an HTML tag -- it provides a given interactivity to the designated HTML element. "It's how we bind behavior"

Angular Expression: "Allows you to insert dynamic values into your HTML." - This is how Angular does data binding (?). 

View Model: The part of the application the user actually sees and interacts with paired with the data shown to the user

**Comment by amaseda** [comment]
:+1:
