### ISSUE TITLE
Angular HW

### ISSUE THREAD

**Issue by pootsmagoots** [ga-wdi-exercises/shaping-up-with-angular#39]
Module - keeps our code encapsulated. Makes our code more maintainable, readable and testable.. Also where we find our dependancies.

Controller - is defined by a JS constructor function that is used to augment the Angular JS scope. Essentially use controllers to set up initial start of the scope object. Add behavior to scope.

Data Binding- is the synchronization between the model and the view.

Directive- is a marker on a HTML tag that tell Angular to run or reference some Javascript code.

Angular Expression (i.e., {{ }}) JS like code snippets mainly placed in interpolation bindings, but also used directly in directive attributes.

View Model-the Scope object. This one sort of confused me a little.. I think it acts like the controller in ruby, but i’m not entirely sure.

**Comment by superbuggy** [comment]
The ViewModel is like a messenger between the Model and the View. `$scope` is like the tracks for the the ViewModel, if the ViewModel was a train.

**Comment by superbuggy** [comment]
👍 awesome work!
