### ISSUE TITLE
HW 15 (Michael L)

### ISSUE THREAD

**Issue by MichaelZLai** [ga-wdi-exercises/shaping-up-with-angular#4]
**Module** - Pieces of our application. Encapsulates parts of our code to make it easier to read, maintain and test. Also define dependencies.
TEACH ME LIKE IM 5: Like a pill dispenser. You know what pills to take per day and how they play on each other.

**Controller** - Helps get data onto the page. Define app's behavior by defining functions and values.
TEACH ME LIKE IM 5: A controller is like a Pinata. The data inside a controller is candy inside a pinata.

**Data Binding** - Expressions are reevaluated when a property changes.
TEACH ME LIKE IM 5: A lookout for a castle. Will update the king if enemies are nearby or not.

**Directive** - A marker on an HTML tag that tells Angular to run or reference some javascript code. 
TEACH ME LIKE IM 5: People playing laser tag. Once a laser hits a person wearing a vest, the vest deactivates.

**Angular Expression** (i.e., {{ }}) - Syntax to call an angular javascript function.
TEACH ME LIKE IM 5: Google Translator. nuff said

**View Model** - A model which has been tailored to support a specific UI, helping in easing data binding.
TEACH ME LIKE IM 5:

**Comment by nolds9** [comment]
👍
