### ISSUE TITLE
Nat Carter

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/shaping-up-with-angular#40]
- Module: The container for pieces of an Angular application, including its controllers. Modules promote encapsulation, readability, maintainability, and testability.
- Controller: handles the data, logic, and behavior for a particular scope in an Angular app.
- Data-binding: The syncing of data between the model and view components of an Angular app.
- Directive: An HTML attribute, starting with 'ng-', that tells Angular to run or reference a particular chunk of JavaScript.
- Expression: Angular's way of binding data to HTML. Delimited like {{this}} and similar to <%= this %> in embedded Ruby.
- View Model: Not really sure. I think it has something to do with data-binding, but beyond that I am lost. I Googled around a bit, but I couldn't find a clear answer.

**Comment by amaseda** [comment]
:+1:
