### ISSUE TITLE
Angular HW Collin O

### ISSUE THREAD

**Issue by cMoney667** [ga-wdi-exercises/shaping-up-with-angular#41]
Module: A collection of services, directives, controllers, filters and configuration information.
Controller: is defined by a Javascript constructor function that is used to augment the scope
Data Binding: The automatic synchronization of data between the model and view components. AngularJS implements data-binding lets you treat the model as the single-source-of-truth in your application.
Directive: they are markers on a DOM element that tells Angular HTML compiler to attach specific behavior to that DOM element
Angular Expression: Expressions are JavaScript-like code snippets that are mainly placed in interpolation bindings (i.e., {{ 1+2 }},{{a+b}},{{user.name}},{{items[index]}})
View Model: is the data that is shown to the user and which they interact with on the web page.

**Comment by phantomhaircuts** [comment]
👍
