### ISSUE TITLE
Mitchell Carroll- Shaping Up with Angular HW

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-wdi-exercises/shaping-up-with-angular#42]
- Modules are where we write pieces of our Angular application. Modules make our code more maintainable, testable, and readable.

- Applications are controlled by controllers (i.e. the ng-controller). A controller is a JS object. 

- Data Binding is the synchronization between the model and the view. 

- Directives let you extend HTML with new attributes which offer functionality to applications. 

- Expressions bind data to HTML. Angular expressions can be written inside double braces {{ expression }}. 

- View Model is what the user see as they interact with the application.

**Comment by AndyWhitley** [comment]
👍
