### ISSUE TITLE
Dan Lin

### ISSUE THREAD

**Issue by dlin2102** [ga-wdi-exercises/shaping-up-with-angular#43]
**Module** - A module is a collection of services, directives, controllers, filters, and configuration information.
**Controller** - They are functions that are bounded by a scope.
**Data Binding** - The automatic synchronization of data between model and view components. 
**Directive** -They are extended HTML attributes with the prefix ng-.They are built in and you can define them.
**Angular Expression (i.e., {{ }})** - The same thing as <%= %>.
**View Model**is the scope object which you can access from either the controller or the view (it's kind of like the glue that links the controller to the view).

**Comment by AndyWhitley** [comment]
👍
