### ISSUE TITLE
Malcom Johnson HW

### ISSUE THREAD

**Issue by malrese1** [ga-wdi-exercises/shaping-up-with-angular#44]
Modules: Where we put most of the code, makes code more maintainable, testable etc.

Controller: this defines the application controller.

Data Binding: holds the model and view

Directives: HTML tag that tells Angular to run or reference some Javascript code.

Expressions: you can put dynamic values into your HTML.

View Model:  what the user interacts with and views.

**Comment by AndyWhitley** [comment]
👍
