### ISSUE TITLE
Habtamu Abere ~ CR6 ~ Angular

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/shaping-up-with-angular#45]
1. Module - is where we write pieces of our angular application
                 - acts as a container for the different parts of our app – controllers, services,filters, directives, etc.
                 - where we define our dependencies

2. Controller -  These are JavaScript functions that are bound to a particular scope.
                     - they are bound to the DOM element they are referenced

3. Data binding - It is the automatic synchronization of data between model and view components.

4. A directive -  is a piece of code that tells  angular to run or reference a javascript code.
                        - directives are markers on a DOM element that tell AngularJS to attach a specified behavior to that  DOM element

5. Expressions - is how we insert dynamic values in our html. 
                          - JavaScript expressions are evaluated against the global window. In AngularJS, expressions are   evaluated against a scope object.
                         e.g.  <p>{{"hello" + "world"}}</p>

6. View Model - Unlike the previous MVC models that we learned in which the controller is responsible for calling on methods once a view event is fired and when  that event fired, you would try to interpret the event and parse the DOM for state so that you could perform some imperative operation.
            In view model The controller no longer is responsible for listening to the view, but rather the view is responsible for issuing specific commands to the controller that it operates on.

**Comment by amaseda** [comment]
:+1:
