### ISSUE TITLE
Aaron Andrews

### ISSUE THREAD

**Issue by andrews94** [ga-wdi-exercises/shaping-up-with-angular#46]
module- collection of services, directives, controllers, filters, and configuration information

controller- defines and apps behavior by defining functions and values

data binding- the synchronization of the model and view

directive- marker on an html tag that tells it to run JS

angular expression- contains the data passed in from the controller to the HTML displayed on the web page.

view model- the angular expression outputs to the view model

**Comment by superbuggy** [comment]
👌 beautiful. I'd say the ViewModel really just implements Angular's two-way data binding. It's like a light-speed messenger between views and models.

**Comment by andrews94** [comment]
Appreciate it.  Thanks for the quick feedback.  Definitely helps when its still fresh in your mind
