### ISSUE TITLE
Ben Shapiro - Angular HW

### ISSUE THREAD

**Issue by pretorben** [ga-wdi-exercises/shaping-up-with-angular#47]
Module- These are where the Angular application is written and where dependencies are defined.  They help with reading, maintaining, and testing the code.

Controller- Define application behavior through functions and values.

Data Binding- If a property is changed, its associated expressions are re-evaluated.

Directive- Tells Angular to run or reference something in JavaScript via a marker in an HTML tag.

Angular Expression (i.e., {{ }})- Insert dynamic values into HTML, such as mathematical operations or joining strings.

View Model- I believe this is where the output to the user is generated.  It seems like this also impacts use of the DOM and allows the view to send specific commands to its controller instead of the controller having to listen to the view.

**Comment by superbuggy** [comment]
The View Model is basically just a messenger between the view and models, and implements 2-way data binding. 👌 nice work!
