### ISSUE TITLE
AngularJS HW - Erica Norby

### ISSUE THREAD

**Issue by ericanorby** [ga-wdi-exercises/shaping-up-with-angular#48]
•	Module – a module is where we write pieces of our Angular application. It is the area where we define dependencies for the app and makes the code more maintainable.
•	Controller – controllers are regular JS object literals that control the data of the application.
•	Data Binding – data binding is the synchronization between the model and the view, so when one of them is changed, the other is updated automatically.
•	Directive – a marker on a HTML tag that tells Angular to run or reference some JavaScript code.
•	Angular Expression (i.e., {{ }}) – expressions allow you to insert dynamic values into HTML
•	View Model – data that is shown to the user in the view

**Comment by phantomhaircuts** [comment]
👍
