### ISSUE TITLE
Angular JS HW

### ISSUE THREAD

**Issue by 585873** [ga-wdi-exercises/shaping-up-with-angular#49]
1.	Angular module is something that defines application which also contains different parts of application.
2.	Controller are that control the data of the application
3.	Data binding is the synchronization of the model and view which effects both of them when one of is updated/changed.
4.	Directive is a marker on html tag that tell it to run js
5.	Angular expression are like code snippets and that allows you to change values into HTML
6.	View model sends commands to the controller and view

**Comment by phantomhaircuts** [comment]
👍
