### ISSUE TITLE
Dominick Angularjs HW

### ISSUE THREAD

**Issue by dhouston14** [ga-wdi-exercises/shaping-up-with-angular#50]
1. Module- this defines an application and also is where we define out dependencies.
2. Controller- An javascript object that contains properties and functions.
3. Data Binding- an automatic sync of data between views and models.
4. Directive- This helps extend the functionality of our html. For example if we insert dynamic values
5. Angular Expression-  Contain literals, operators, and variables.
6. View Model - this is the connection for a controller and a view in angularjs.

**Comment by phantomhaircuts** [comment]
👍
