### ISSUE TITLE
Clark HW

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/shaping-up-with-angular#52]
Module - where you write pieces of the code to keep it encapsulated. It makes its easier to read, write, and test. Where app components live
Controller - help get data on to the page. its where you define behavior by defining functions and values. Where you add behvaior
Data Binding-  how you math up the model with the view
Directive - HTML annotations that trigger JS behavior--- Tells angular what to do and where to pull the data from; seem to be like methods in ruby 
Angular Expression (i.e., {{ }}) - what/how gets processed and rendered on the page
View Model - ng route? I have no idea I feel like I missed this but I imagine its how you model what you want to be viewed through the HTML

**Comment by amaseda** [comment]
:+1:
