### ISSUE TITLE
jays ng

### ISSUE THREAD

**Issue by xgironx** [ga-wdi-exercises/shaping-up-with-angular#53]
Module
1. equiv to a CLASS in othe langs
2. has decorator functions
3. takes in commands to compile code,like Typescript into Javascript
4. knows about its own components, directives and pipes.  i don't know what these are yet, but figure they somehow equiv to sub-classes, methods and functions in some order

CONTROLLER
1. is a javascript object's function that holds business logic
2. gets attached to the DOM when it gets the ng-controller directive or "controller as" syntax
3. has something to do with SCOPE but not sure yet how
4. establishes initial values for properties of $scope for the VIEW MODEL
5. defines methods for $scope
6. works like the Controllers we used in RoR
7. doesnt touch data

Data Binding
1. is the conversation bw MODEL & VIEW and can go in 2 directions, two-way data binding, where both MODEL & VIEW can update data
2. the CONTROLLER has no play here

Directive
1. like the SELECTORs we saw in css & DOM-land
2. tells the NG COMPILER how to do its job
3. perform manual DOM changes

Angular Expression (i.e., {{ }})
1. like the simple, .notation and params[] EXPRESSIONS and INTERPOLATIONs we've used in js and Ruby
2. unlike js, ng doesnt use callback functions
3. bummed to see you cant use regex in ng expressions

View Model
1. this is that $scope objecti dont understand yet, that both
2. has to listen to what either the VIEW or CONTROLLER say to it
3. stages data in the $scope object for the VIEW to displdisplay
4. its the secret handshake convo bw VIEW & CONTROLLER

**Comment by superbuggy** [comment]
All the stuff you had about modules is true for `Angular2` but not `Angular1`

> unlike js, ng doesnt use callback functions

It definitely uses callbacks on the javascript side of things, but you're right, you wouldn't use them  in angular expressions, e.g. `{{ 5 * 5}}`

**Comment by superbuggy** [comment]
>this is that $scope objecti dont understand yet, that both
has to listen to what either the VIEW or CONTROLLER say to it
stages data in the $scope object for the VIEW to displdisplay
its the secret handshake convo bw VIEW & CONTROLLER

Nice! We're going to avoid using `$scope` explicitly but it's kind of the thread that binds all the parts of angular together. Changing the ViewModel is registered on `$scope`, even if we're not using it explicitly, it's operating under the hood. It's like the tracks for the ViewModel,  if the ViewModel was a train.

**Comment by superbuggy** [comment]
👍

**Comment by xgironx** [comment]
James
Thank you for reading this so carefully.   I appreciate your corrections :o)
Jay
