### ISSUE TITLE
Shaping Up With Angular HW - Elena Santana

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/shaping-up-with-angular#54]
Module: a place to write pieces of Angular app. Also a place to declare dependancies. First thing to write in an Angular app, with an empty array for dependancies because... convention again?

Controller: pretty much like in Rails, defines behaviours. Functions and values are written in the controller. Capital CamelCase. Scoped to a div it's assigned to.

Data Binding: expressions are re-evaluated when properties change.

Directive: a snippet of code added to HTML very much like a class / id property that indicates to Angular to run reference to some JS function in the controller.

Expression: allows us to insert dynamic data into the HTML.

View Model: ???? I guess that's what user sees when interacting with website?

**Comment by amaseda** [comment]
:+1:
