### ISSUE TITLE
Jared Edwards HW - Shaping up with Angular

### ISSUE THREAD

**Issue by jarededwards** [ga-wdi-exercises/shaping-up-with-angular#55]
Module - This is where we write pieces of our angular application. It Encapsulates our code which makes it more maintainable, readable and testable. We also define any dependencies here

Controller - This is where we define the behavior of our application by defining functions and values.

Data Binding - Expressions define a 2-way data binding relationship. It allows the expressions to re-evalue a property and change dynamically.

Directive - Directives are the markers within our HTML that tell angular what to reference for an action or behavior.

Angular Expression (i.e., {{ }}) - Expressions are how we allow values to be dynamically changed on the web page in real time.

View Model -a view is what is showing inside of the DOM (what the user sees). the model is what hosts the view and allows interation with the user

**Comment by nayana487** [comment]
👍
