### ISSUE TITLE
Shaping Up With Angular — Rodney Curl

### ISSUE THREAD

**Issue by rodneycurl** [ga-wdi-exercises/shaping-up-with-angular#56]
Modules is where we write pieces of our Angular application. This makes our code more maintainable, testable, and readable. Its also where we define dependencies for our app.

Controllers are were we define our applications’ behavior by defining functions and values.

Data Binding expressions are re-evaluated when properties change.

Directive is a marker on HTML tag that tells Angular to run or reference some JavaScript code.

Angular Expression (i.e., {{ }}) allow you to insert dynamic values into your HTML.

View Model is what user sees when interacting with a website or application.

Angular is a client-side JavaScript Framework for adding interactivity to HTML.

**Comment by nayana487** [comment]
👍
