### ISSUE TITLE
Angularjs HW - Chris Wightman

### ISSUE THREAD

**Issue by cjwightman** [ga-wdi-exercises/shaping-up-with-angular#57]
* Module - A module is an encapsulated piece of code for an Angular application. It allows for better code organization and makes it more modular. More, readable, maintainable and testable. Application dependencies are found within the modules.
* Controller - Where we define our functions and values that will tell our app how to behave. The controller must be inside our app which is why it’s important to get into the habit of wrapping our entire app in parentheses. Controller names always contain the word “controller” and are in capital case.
* Data Binding
    * Directive - A Directive is a marker on a HTML tag that tells Angular to run or reference some JavaScript code. A directive is added as an attribute referencing a function to then perform an action.
* Angular Expression (i.e., {{ }}) - Expressions allow us to add dynamic values and functions into the HTML code that will then render the result of function or value.
* View Model - Didn't make it this far.

**Comment by phantomhaircuts** [comment]
👍
