### ISSUE TITLE
Fiona N

### ISSUE THREAD

**Issue by nfiona** [ga-wdi-exercises/shaping-up-with-angular#58]
- Module : collection of services, directives, controllers, filters, and configuration information
- Controller: In AngularJS, a Controller is defined by a JavaScript constructor function that is used to augment the AngularJS Scope
- Data Binding: a process that connects application UI and business logic.
- Directive: extended HTML attributes with the prefix ng- 
- Angular expressions: contain the data passed in from the controller to the HTML displayed on the web page.
- View Model: sends commands to the controller and a view.

**Comment by nayana487** [comment]
👍
