### ISSUE TITLE
Justin Shin

### ISSUE THREAD

**Issue by Justin-Shin** [ga-wdi-exercises/shaping-up-with-angular#59]
I got home and fell asleep almost immediately

Module: 
Where we write pieces of our Angular application.
Makes our code more maintainable, testable, and readable.
Where we define dependencies for our app.

Controller - Controllers are where we define our app’s behavior by defining functions and values.

Data Binding - 

Directive - A marker on a HTML tag that tells Angular to run or reference some JavaScript code

Angular Expression (i.e., {{ }}) - Allow you to insert dynamic values into your HTML.

View Model -

**Comment by superbuggy** [comment]
ViewModel is a like hyperfast messenger between the view and model; it implements 2 way data-binding. 👍
