### ISSUE TITLE
Angular - Kevin Keller

### ISSUE THREAD

**Issue by kkeller93** [ga-wdi-exercises/shaping-up-with-angular#61]
Module: collection of services, directives, controllers, filters, and configuration information
Controller: helps information get onto the page. behavior is defined by the defining functions and values
Data Binding: when expressions are changed the values are re-evaluated
Directive: helps extend the functionality of the HTML
Angular Expression (i.e., {{ }}): Contains operators, variables and literals
View Model: the view in angularjs and the connection for the controller

**Comment by phantomhaircuts** [comment]
👍
