### ISSUE TITLE
Clements - Angular

### ISSUE THREAD

**Issue by sdkclements** [ga-wdi-exercises/shaping-up-with-angular#62]
Module: A module is a collection of services, directives, controllers, filters, and configuration information. angular.module is used to configure the $injector.
Controller: created by a JS contructor the controller manages the front end data
Data Binding: Angular uses its magic to always ensure that the model and view accuratley represent each other.
Directive: ng- are various extended html attributes- basically built in functions
Angular Expression (i.e., {{ }}) The syntax for writing angular expressions directly in the DOM
View Model

**Comment by amaseda** [comment]
:+1:
