### ISSUE TITLE
Angular intro - the wolf

### ISSUE THREAD

**Issue by AskForTheWolf** [ga-wdi-exercises/shaping-up-with-angular#83]
Module - Basically a collection of stuff that you can do.  Services, controllers, information, that you can query and use.

Controller - A constructor function used to modify scope.  Or set it up.

Data binding - The synchronization of data between model and view. Helps to not have to write code that constantly syncs the view with the model, and vice-versa.

Directive - Specifics things (tags, attributes, comments) that tell the compiler what to do to them, or how to do to them.

Angular Expression - Bits of code, like vanilla JS, attached to bindings.  However they are evaluated differently.

View Model - Kind of interpolates changes between model and view so that the model or view isn't constantly changing every time something gets changed.

**Comment by superbuggy** [comment]
👍
