### ISSUE TITLE
AngularJs definitions

### ISSUE THREAD

**Issue by Fitssum** [ga-wdi-exercises/shaping-up-with-angular#87]
Modules: are where we write pieces of our AngularJs application. It's how we keep our code capsulated so that our code can become maintainable, testable and readable. It is a container for the application controllers. It's where we define the dependencies of our application. 

Controller: is a Javascript object containing attributes, properties and functions which is defined using ng-controller directive.

Data Binding: is the automatic synchronization of data between the model and view components.

Directive: is a marker on HTML tag that tells AngularJS to run or reference some javascript code. It appears in the <body> tag (similar like the js expression).

Angular Expression: are dynamic values in the HTML. Numerical operations can be an example. 

View Model: is the projection of the model at all times. When the model changes, it is reflected in the views and vice versa.

**Comment by superbuggy** [comment]
👍
