### ISSUE TITLE
Angular HW (Poh)

### ISSUE THREAD

**Issue by pohckuan** [ga-wdi-exercises/shaping-up-with-angular#9]
Directive offers functionality to the application by using the prefix 'ng-' . 

Controllers are regular javascript objects that contain attributes and properties and can be carried by directives. They control the data and flow of application.

A module acts as containers for services, directives, controllers, filters, and configuration information to keep code clean. A module is created by using angular.module. 

Data Binding is the synchronization between a model and a view. When the model changes, the view reflects the change, and vice versa. 

Angular Expression are written in double braces that can carry out numerical and string operations, such has {{5+5}} and {{ first name + ""+ last name}}. However, the operations can only be carried out with directives.

View Model is a scope object which can be accessed from either controller or view. The scope is an  object with properties and methods and starts with $. It is passed as an argument in the controller , the properties added will show in the view.

**Comment by nolds9** [comment]
👍
